# Generated by Django 3.2.5 on 2022-07-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('vcffile', models.FileField(null=True, unique=True, upload_to='contact/', verbose_name='Contact File')),
            ],
        ),
    ]
