# Generated by Django 4.2.8 on 2024-03-03 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_created_at_user_modified_at_firstpassword"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstpassword",
            name="created_at",
        ),
    ]
