# Generated by Django 4.2.8 on 2024-03-03 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_firstpassword_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="firstpassword",
            options={
                "verbose_name": "First Password",
                "verbose_name_plural": "First Password",
            },
        ),
        migrations.AddField(
            model_name="firstpassword",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="firstpassword",
            name="password",
            field=models.CharField(max_length=25),
        ),
    ]
