# Generated by Django 3.2 on 2023-02-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230205_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_line1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email2',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Secondary Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebooklink',
            field=models.URLField(blank=True, max_length=250, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagramlink',
            field=models.URLField(blank=True, max_length=250, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedinlink',
            field=models.URLField(blank=True, max_length=250, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, verbose_name='Secondary Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='skypelink',
            field=models.URLField(blank=True, max_length=250, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitterlink',
            field=models.URLField(blank=True, max_length=250, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='youtubelink',
            field=models.URLField(blank=True, max_length=250, verbose_name='Youtube'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='zipcode',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
