# Generated by Django 3.2 on 2023-02-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230205_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactModel',
        ),
    ]
