# Generated by Django 4.2.8 on 2024-03-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_contact_created_at_contact_modified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="url",
            field=models.URLField(blank=True, max_length=255, verbose_name="URL"),
        ),
    ]
