# Generated by Django 3.2 on 2023-02-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_contact_contactmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='Contact',
        ),
    ]
