# Generated by Django 3.2 on 2023-02-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_contactmodel_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='brochure_file',
            field=models.FileField(blank=True, null=True, upload_to='brochure/', verbose_name='Brochure File'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_file',
            field=models.FileField(blank=True, null=True, upload_to='profile/', verbose_name='Contact File'),
        ),
    ]
