# Generated by Django 3.2 on 2023-02-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230206_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, max_length=250, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
