# Generated by Django 3.2 on 2023-02-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='brochure_file',
            field=models.FileField(blank=True, null=True, upload_to='media/brochure/', verbose_name='Brochure File'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_file',
            field=models.FileField(blank=True, null=True, upload_to='media/contact/', verbose_name='Contact File'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pic/', verbose_name='Profile Pic'),
        ),
    ]
