# Generated by Django 3.2 on 2023-02-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230208_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='updated_at',
            new_name='last_login',
        ),
    ]
