# Generated by Django 3.2 on 2023-02-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_updated_at_contact_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_login',
        ),
    ]
