# Generated by Django 3.2 on 2023-02-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20230208_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/', verbose_name='Profile Pic'),
        ),
    ]
