# Generated by Django 3.2 on 2023-02-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_contact_brochure_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='brochure_file',
            field=models.FileField(blank=True, null=True, upload_to='brochure/', verbose_name='Brochure File'),
        ),
    ]
