# Generated by Django 3.2 on 2023-02-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20230215_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='about',
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.URLField(blank=True, max_length=250, verbose_name='Location'),
        ),
    ]
